### ISSUE TITLE
Не могу начать новую игру

### ISSUE THREAD

**Issue by aNNiPAk** [aikikode/nautili#1]
При создании новой игры, при нажатии на карту-окно игры закрывается.(python ошибок не пишет) что делать?

**Comment by aikikode** [comment]
Добрый день, пришлите, пожалуйста, больше информации:
- какая у вас ОС
- какую версия питона используете:

``` bash
python --version
```
- какие пакеты установлены:

``` bash
pip freeze -l
```

**Comment by aNNiPAk** [comment]
Здравствуйте, 
ось: windows 8.1
python v 2.7
пакеты
![2014-11-29_131943](https://cloud.githubusercontent.com/assets/9993719/5234157/9bdab628-77ca-11e4-929b-054093d0002c.png)
PyTMX установить как я понял в эту папку, поправьте если не так
![2014-11-29_132210](https://cloud.githubusercontent.com/assets/9993719/5234166/e3212968-77ca-11e4-9ab2-8f489041e64f.png)
Почему такой интерес к этой игре: в детстве сам делал карту и вырезал кораблики, но по нормальному поиграть так и не удавалось, сейчас я подрос так скажем и решил сделать эту игру на ПК, при поиске инфы и встретил вашу разработку, но протестить ее так и неудалось((

**Comment by aikikode** [comment]
Спасибо за информацию.

Вы все сделали правильно. Проблема оказалась в том, что текущая версия PyTMX (3.20.5) уже не работает с кодом nautili. Необходимо ставить версию 2.16.2, что (т.к. к сожалению разработчики PyTMX не пользуются системой тегов на github) в Windows может быть проблематично. Нужно сделать следующие действия:
1) удалить скачанную папку PyTMX
2) установить pip (в сети много инструкций по установке)
3) с помощью pip поставить PyTMX версии 2.16.2

P.S. nautili изначально писалась и лучше всего работает под Linux. Если у вас есть Linux или виртуалка с Linux, запускайте корабликов с нее. Я постараюсь обновить код для работы с новой версией, чтобы не было таких проблем, но не могу обещать, что это будет в ближайшее время.

**Comment by aikikode** [comment]
Добавил поддержку последней версии PyTMX (3.20.5). Скачайте новую версию корабликов и попробуйте еще раз.

На всякий случай удалите уже скачанную папку pytmx, и так же, как и раньше, скопируйте папку pytmx последней версии:
https://github.com/bitcraft/PyTMX/tree/master/pytmx
во внутренюю папку nautili.
